function ReportHeader({ datasetInfo }) {

    if (!datasetInfo) return null;

    const today = new Date();

    return (

        <div className="bg-white rounded-2xl shadow-lg p-8">

            <div className="flex justify-between items-center">

                <div>

                    <h1 className="text-4xl font-bold">

                        Business Report

                    </h1>

                    <p className="text-gray-500 mt-2">

                        AI Powered Business Intelligence Report

                    </p>

                </div>

                <div className="text-right">

                    <p className="font-semibold">

                        Generated On

                    </p>

                    <p className="text-gray-500">

                        {today.toLocaleDateString()}

                    </p>

                </div>

            </div>

            <hr className="my-6" />

            <div className="grid md:grid-cols-3 gap-6">

                <div>

                    <p className="text-gray-500">

                        Dataset

                    </p>

                    <h3 className="text-xl font-bold">

                        {datasetInfo.filename}

                    </h3>

                </div>

                <div>

                    <p className="text-gray-500">

                        Generated By

                    </p>

                    <h3 className="text-xl font-bold">

                        InsightIQ

                    </h3>

                </div>

                <div>

                    <p className="text-gray-500">

                        Status

                    </p>

                    <span className="bg-green-100 text-green-700 px-4 py-2 rounded-full font-semibold">

                        Ready

                    </span>

                </div>

            </div>

        </div>

    );

}

export default ReportHeader;